version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    environment:
      - POSTGRES_USER=admin_blog
      - POSTGRES_PASSWORD=admin_blog
      - POSTGRES_DB=blog_django_dev
  web:
    build: .
    command: python /code/blog/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  

volumes:
  postgres_data:
