# Generated by Django 3.1.2 on 2020-10-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ['-date']},
        ),
    ]
