# Generated by Django 3.1.2 on 2020-10-27 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_read',
            field=models.ManyToManyField(blank=True, related_name='post_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
